### ISSUE TITLE
Hungarian model with spaCy

### ISSUE THREAD

**Issue by oroszgy** [nikitakit/self-attentive-parser#17]
Hi,

Just letting you know that parsing Hungarian should be available through spaCy, as it can [tokenize Hungarian](https://github.com/explosion/spaCy/issues?utf8=%E2%9C%93&q=label%3A%22lang+%2F+hu%22+) and [PoS tagging with Dependency parsing is also available through a 3rd party packages](https://github.com/oroszgy/spacy-hungarian-models)

Thanks,
Gyuri

**Comment by nikitakit** [comment]
Closing this now that I've added the link to the README. Thanks for telling me about the spaCy models (and let me know if you ever spot any issues with the Hungarian parser).
