### ISSUE TITLE
Spacy - BeneparComponent updates pos_ attribute of spacy tagger output

### ISSUE THREAD

**Issue by sahinbatmaz** [nikitakit/self-attentive-parser#19]
As I read the benepar documents, benepar should not update pos_ attribute, it should only set `span._.*` and `token._.*` custom attributes.

```
import spacy
from benepar.spacy_plugin import BeneparComponent
```
```
spacynlp = spacy.load('en_core_web_sm')
spacynlp.add_pipe(BeneparComponent("benepar_en2"))

tokenizedtext = ['Bütün', 'insanlar', 'hür', ',', 'haysiyet', 've', 'haklar', 'bakımından','eşit', 'doğarlar','.']
doc = spacy.tokens.doc.Doc(spacynlp.vocab, words=tokenizedtext )
for name, proc in spacynlp.pipeline:
      doc = proc(doc)
      print(name, doc[0].pos_)
```

The output is like this;
```
tagger  NOUN
parser  NOUN
ner     NOUN
benepar PROPN
```

Why does this happen?

**Comment by nikitakit** [comment]
You can pass `disable_tagger=True` to the BeneparComponent constructor to disable this.

The newer benepar models have built in part of speech taggers, which tend to be more accurate than spaCy defaults. I had tried always relying on spaCy tags, but I got a lot of bug reports where the parser would correctly identify the syntax of a sentence but the tags were all wrong. So I added my own tagger, which only took a very small modification to the parser.

**Comment by sahinbatmaz** [comment]
Thanks a lot for the answer, it completely makes sense. I just did not see anything mentioning this in the readme and wondered the reason.

**Comment by sahinbatmaz** [comment]
By the way, I want to compliment to the tool. I really like the tool because it has better constituency performance in my studies compared to similar works; flair chunk tool, allenai semantic-role-labeling tool, nltk tool. So thank you very much.
