### ISSUE TITLE
Error as I follow the "Usage with spaCy" example

### ISSUE THREAD

**Issue by colingoldberg** [nikitakit/self-attentive-parser#2]
Hi,

On macosx 10.13.5 I got an error at the 'nlp.add_pipe(BeneparComponent("benepar_en"))' statement:

`
$ python
Python 3.6.4 |Anaconda custom (64-bit)| (default, Dec 21 2017, 15:39:08) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import benepar
/Users/colingoldberg/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
>>> benepar.download('benepar_en')
[nltk_data] Downloading package benepar_en to
[nltk_data]     /Users/colingoldberg/nltk_data...
True
>>> import spacy
>>> from benepar.spacy_plugin import BeneparComponent
>>> nlp = spacy.load('en')
>>> nlp.add_pipe(BeneparComponent("benepar_en"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/colingoldberg/anaconda3/lib/python3.6/site-packages/benepar/spacy_plugin.py", line 73, in __init__
    super(BeneparComponent, self).__init__(filename, batch_size)
  File "/Users/colingoldberg/anaconda3/lib/python3.6/site-packages/benepar/base_parser.py", line 163, in __init__
    tf.import_graph_def(graph_def, name='')
  File "/Users/colingoldberg/anaconda3/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 316, in new_func
    return func(*args, **kwargs)
  File "/Users/colingoldberg/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/importer.py", line 541, in import_graph_def
    raise ValueError('No op named %s in defined operations.' % node.op)
ValueError: No op named ClipByValue in defined operations.

`

I also tried this on an AWS EC2 (t2.small) instance (2GB memory), and got the following error:

`
# python
Python 3.6.3 |Anaconda custom (64-bit)| (default, Oct 13 2017, 12:02:49) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import benepar
>>> benepar.download('benepar_en')
[nltk_data] Downloading package benepar_en to /root/nltk_data...
[nltk_data]   Package benepar_en is already up-to-date!
True
>>> import spacy
>>> from benepar.spacy_plugin import BeneparComponent
>>> nlp = spacy.load('en')
>>> nlp.add_pipe(BeneparComponent("benepar_en"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/share/anaconda3/lib/python3.6/site-packages/benepar/spacy_plugin.py", line 73, in __init__
    super(BeneparComponent, self).__init__(filename, batch_size)
  File "/usr/local/share/anaconda3/lib/python3.6/site-packages/benepar/base_parser.py", line 163, in __init__
    tf.import_graph_def(graph_def, name='')
  File "/usr/local/share/anaconda3/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 432, in new_func
    return func(*args, **kwargs)
  File "/usr/local/share/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/importer.py", line 486, in import_graph_def
    with c_api_util.tf_buffer(graph_def.SerializeToString()) as serialized:
MemoryError

`

I look forward to having this issue resolved so that I can continue testing.

Thank you.

Colin Goldberg

**Comment by nikitakit** [comment]
The `ValueError: No op named ClipByValue in defined operations.` is caused by running an older version of tensorflow. Tensorflow 1.8.0 is required to run the `benepar_en` model. I'm sorry that the tensorflow installation situation is so messy, but it's difficult to solve at the package-manager level because there are separate tensorflow packages for cpu and gpu.

I can't help about the MemoryError: the parsers are actually quite big when uncompressed. You can download and use `benepar_en_small` instead of `benepar_en` if your machine has insufficient RAM.

**Comment by colingoldberg** [comment]
Thank you. Updating tensorflow worked on my mac, and using benepar_en_small on the 2GB EC2 instance worked as well (even as it gave some memory warnings).

Do you have any recommendations, or experience, for (minimum) memory requirements for benepar_en? 

As a newcomer to this space, I appreciate any documentation and help, especially examples showing the kinds of things I can do with the results of a parse.

**Comment by nikitakit** [comment]
Thanks for pointing out the memory situation. The `benepar_en` model is around 430 MB when uncompressed. In theory this should be most of the memory that's needed to run the model, but unfortunately there seems to be quite a bit of overhead inside Tensorflow. Steady-state memory consumption on my machine is around 3GB, though I'm not sure how much of that can be garbage collected. I anticipate that a 1-2 GB of RAM (for the ~430MB parameters plus active computations) plus a generous amount of swap space should suffice to run the model. EC2 instances don't normally have swap enabled, which explains why the full-size model won't run.

My recommendation for now is to run `benepar_en_small` if you need to reduce memory consumption.

Another thing to note is that if your spaCy documents contain many sentences, or if you're using `parse_sents` from the NLTK integration, benepar will parse a batch of sentences at a time. Both `benepar.Parser` and `BeneparComponent` accept a `batch_size` argument, which can be lowered from the default value of 64 (sentences) to reduce memory usage.

**Comment by nikitakit** [comment]
What do you mean by transforming the parse tree to a dict?

A parse tree is a tree data structure, which has very different properties from a dict. For example, children in a parse tree are ordered (while keys in a dict are not, and also can't repeat).

Here's one way to convert the parse tree to a dict, but this is mostly just an example of how to navigate the parse tree:
```python
import spacy
from benepar.spacy_plugin import BeneparComponent
nlp = spacy.load('en')
nlp.add_pipe(BeneparComponent("benepar_en"))
doc = nlp(u"The time for action is now. It's never too late to do something.")
sent = list(doc.sents)[0]
print(sent._.parse_string)


# Note: doesn't work for the last sentence in a document.
# The bug will be fixed in a new release of benepar, shortly
def to_dict(span, idx=0):
    if len(span) == 1:
        res = str(span)
    else:
        res = {}
        for i, child_span in enumerate(span._.children):
            res.update(to_dict(child_span, i))

    labels = list(span._.labels)
    if len(span) == 1:
        labels.append(span[0].tag_)

    for label in reversed(labels[1:]):
        res = {"0/" + label: res}

    res = {str(idx) + "/" + labels[0]: res}
    return res

print(to_dict(list(doc.sents)[0]))
```

**Comment by colingoldberg** [comment]
I accept the limitations you point out. The reason I want to do this is that I need to report results back to a non-python caller using a json structure, and this is best done via a dict (I believe). As long as I manage what I am submitting to be parsed, this should be ok.
