### ISSUE TITLE
AttributeError: 'LeafParseNode' object has no attribute 'oracle_label'

### ISSUE THREAD

**Issue by xiaoxiaoAurora** [nikitakit/self-attentive-parser#23]
When I tried to run as the follow:
`python src/main.py train --use-elmo --model-path-base models/en_elmo --num-layers 4` 

There was a Error:

```
epoch 1 batch 14/112 processed 2,800 batch-loss 101.9406 grad-norm 93.0121 epoch-elapsed 0h01m57s total-elapsed 0h01m57s
epoch 1 batch 15/112 processed 3,000 batch-loss 90.0741 grad-norm 73.8915 epoch-elapsed 0h02m05s total-elapsed 0h02m05s
sentence:  1 [('PU', '）')]
Traceback (most recent call last):
  File "src/main.py", line 615, in <module>
    main()
  File "src/main.py", line 611, in main
    args.callback(args)
  File "src/main.py", line 564, in <lambda>
    subparser.set_defaults(callback=lambda args: run_train(args, hparams))
  File "src/main.py", line 312, in run_train
    _, loss = parser.parse_batch(subbatch_sentences, subbatch_trees)
  File "/home/workspace/self-attentive-parser/src/parse_nk.py", line 1087, in parse_batch
    p_i, p_j, p_label, p_augment, g_i, g_j, g_label = self.parse_from_annotations(fencepost_annotations_start[start:end,:], fencepost_annotations_end[start:end,:], sentences[i], golds[i])
  File "/home/workspace/self-attentive-parser/src/parse_nk.py", line 1140, in parse_from_annotations
    p_score, p_i, p_j, p_label, p_augment = chart_helper.decode(False, **decoder_args)
  File "src/chart_helper.pyx", line 48, in chart_helper.decode
    oracle_label_chart[left, right] = label_vocab.index(gold.oracle_label(left, right))
AttributeError: 'LeafParseNode' object has no attribute 'oracle_label'
```

**Comment by nikitakit** [comment]
This is a known limitation with how the parser is currently formulated: each tree must contain a non-terminal node at the root. In your example above, the "part-of-speech" tag PU is the root node, which breaks that assumption.

The way I usually work around this is by wrapping all trees with a "TOP" symbol for the root node, and then disabling the "strip_top" flag when the treebank is known to contain examples that don't have a root non-terminal label.

**Comment by xiaoxiaoAurora** [comment]
> This is a known limitation with how the parser is currently formulated: each tree must contain a non-terminal node at the root. In your example above, the "part-of-speech" tag PU is the root node, which breaks that assumption.
> 
> The way I usually work around this is by wrapping all trees with a "TOP" symbol for the root node, and then disabling the "strip_top" flag when the treebank is known to contain examples that don't have a root non-terminal label.

Great! Thank you very much! That is very helpful.
However,  When I tried to train the model on CTB data as the following comand:  

```
python src/main.py train --use-elmo --model-path-base models/ctb_elmo --num-layers 4 --epochs 500
```
I got a result:

```
epoch 134 batch 112/112 processed 2,985,118 batch-loss 6.4597 grad-norm 17.0195 epoch-elapsed 0h05m52s total-elapsed 13h54m52s  
dev-fscore (Recall=84.26, Precision=85.77, FScore=85.01, CompleteMatch=19.32) dev-elapsed 0h00m15s total-elapsed 13h55m07s  
Terminating due to lack of improvement in dev fscore.
```  

and this score is less than your **"91.69 F1 on CTB 5.1 test set in benepar_zh"**  
my CTB data size:
- train data: 22277
- dev data: 1761  

can you provide parameter settings in detail?

**Comment by nikitakit** [comment]
It looks like you're using the English ELMo embeddings to learn a parser for Chinese, which works poorly due to the language mismatch. I recommend that you use the Chinese version of BERT instead. Here is the command needed for training the model: https://github.com/nikitakit/self-attentive-parser/blob/master/EXPERIMENTS.md#chinese-models

It also looks like our dataset sizes don't match. See [here](https://github.com/nikitakit/parser-data-gen/tree/master/corpora/ctb_5.1) for CTB data preparation scripts. My data sizes are 17544 train / 352 dev / 348 test.
