### ISSUE TITLE
Do the default models include BERT embeddings?

### ISSUE THREAD

**Issue by dav-ell** [nikitakit/self-attentive-parser#24]
Just curious if the default models (specifically `benepar_en2` or `benepar_en2_large`) include BERT embeddings? I see references to BERT and ELMo in the training section. Do we need to do that training ourselves if we want a parser to use those embeddings, or are they already included?

And more importantly, even if the default models don't include BERT/ELMo embeddings, is it worth doing the training?

Thanks!

**Comment by nikitakit** [comment]
These are both BERT-based models; sorry that this isn't clear. `benepar_en2` is based on BERT-base-uncased, and `benepar_en2_large` is based on BERT-large-uncased.

**Comment by dav-ell** [comment]
Great, thanks for clarifying.
