### ISSUE TITLE
Can't access leaf labels

### ISSUE THREAD

**Issue by eawer** [nikitakit/self-attentive-parser#27]
Hello! I need to access each tree node label while traversing the tree. And the problem I faced is that I don't have an access to the leaf node's labels.

I have following code:

```
import spacy
from benepar.spacy_plugin import BeneparComponent
nlp = spacy.load('en')
nlp.add_pipe(BeneparComponent("benepar_en2"))

text = 'John Moss hates him.'
doc = nlp(text)
for sent in doc.sents:
  print(sent._.parse_string)
  child_1 = list(sent._.children)[0]
  print(child_1._.parse_string, child_1._.labels)
  child_2 = list(child_1._.children)[0]
  print(child_2._.parse_string, child_2._.labels)
```

which gives such output:
```
(S (NP (NNP John) (NNP Moss)) (VP (VBZ hates) (NP (PRP him))) (. .))
(NP (NNP John) (NNP Moss)) ('NP',)
(NNP John) ()
```
As you can see, last parse string has NNP, but the labels tuple is empty

is it a bug or am I doing it wrong?

**Comment by nikitakit** [comment]
The part-of-speech tags are accessible via the `tag_` attribute in spaCy, e.g. something like `child_2.tag_`. I've set things up so that `._.labels` on includes the non-terminal/bracket labels, and not POS tags like NNP.

**Comment by eawer** [comment]
So is it correct to say, that if the node has an empty tuple in `labels` - it is a leaf?

**Comment by nikitakit** [comment]
That's right, only single tokens can have an empty tuple in `labels`.

Of course, single tokens can have non-empty `labels`, too: e.g. `(NP (NN xxx))` will have a tag `NN` and a labels tuple `("NP",)`.
