### ISSUE TITLE
Deprecation warnings

### ISSUE THREAD

**Issue by colingoldberg** [nikitakit/self-attentive-parser#33]
Hi,

Not sure what impact these messages have (so far) - I am reporting them FYI:

(On macosx 10.14.5, python 3.6.7, tensorflow 1.14.0)

>>> nlp.add_pipe(BeneparComponent("benepar_en"))
    WARNING: Logging before flag parsing goes to stderr.
    W0718 09:41:51.815104 4736062912 deprecation_wrapper.py:119] From 
    /Users/.../anaconda3/lib/python3.6/site-packages/benepar/base_parser.py:199: The name 
    tf.GraphDef is deprecated. Please use tf.compat.v1.GraphDef instead.

    W0718 09:41:53.919924 4736062912 deprecation_wrapper.py:119] From 
    /Users/.../anaconda3/lib/python3.6/site-packages/benepar/base_parser.py:202: The name 
    tf.Session is deprecated. Please use tf.compat.v1.Session instead.

Regards

Colin Goldberg

**Comment by BramVanroy** [comment]
Probably these occur because this module was built with TF v1 in mind, but you installed v2. I agree that a better compatibility should be found. Perhaps by simply making the dependencies more fixed (e.g. 2 > version >= 1.11).

**Comment by nikitakit** [comment]
Thanks for pointing this out!

I'll keep this in mind, and I'll try dealing with this around the time the tf2.0 release candidate comes out. I still need to think about what I want to do in terms of model compatibility, and whether it makes sense to change how the models are packaged (e.g. switching to the SavedModel format).
