### ISSUE TITLE
use all gpu with Spacy

### ISSUE THREAD

**Issue by allanj** [nikitakit/self-attentive-parser#39]
I follow the instructions on Spacy (https://spacy.io/universe/project/self-attentive-parser) and use the `benepar_en` model. 

When I use this model, it basically uses all the GPUs although they just utilize 163 MB for each GPU. Can I specify which GPU to use in practice?

**Comment by nikitakit** [comment]
One option would be to set the `CUDA_VISIBLE_DEVICES` environment variable to restrict the GPUs that are in use.

You can also modify the tensorflow session initialization [here](https://github.com/nikitakit/self-attentive-parser/blob/master/benepar/base_parser.py#L204) to only use a single GPU.

**Comment by allanj** [comment]
Thanks, using `CUDA_VISIBLE_DEVICES` works for me.
