### ISSUE TITLE
module 'tensorflow' has no attribute 'GraphDef'

### ISSUE THREAD

**Issue by LeonCrashCode** [nikitakit/self-attentive-parser#43]
I got the error from tensorflow: module 'tensorflow' has no attribute 'GraphDef'. My tensorflow version is 2.0.0, is it any quick way to fix it?

**Comment by LeonCrashCode** [comment]
I have solved the problem by modifying to tf.compat.v1.GraphDef.

**Comment by sahinbatmaz** [comment]
I have this error. It seems benepar can not be used with tensorflow 2.0.0

**Comment by mariiakashpur** [comment]
I am facing the same issue. Which tensorflow version is required?

**Comment by plandes** [comment]
I also had this problem and based on [this thread](https://stackoverflow.com/questions/57614436/od-graph-def-tf-graphdef-attributeerror-module-tensorflow-has-no-attribut) I created a [pull request](https://github.com/nikitakit/self-attentive-parser/pull/72).

If the author takes a while to merge the request, you can install it manually with:
```bash
pip uninstall -y benepar 
git clone https://github.com/plandes/self-attentive-parser
cd self-attentive-parser
python setup.py install
```
