### ISSUE TITLE
ctb result

### ISSUE THREAD

**Issue by HongyanJiao** [nikitakit/self-attentive-parser#45]
I used default parameters and 8 layers bert ，trained on data ctb5.1.
I got 'FScore=90.50, CompleteMatch=28.82'
But the paper 'Cross-Domain Generalization of Neural Constituency Parsers' 
refered F1=92.14, exactmatch=44.42
I was confused if there were anything wrong on my training, have you fine-tuned bert?

**Comment by KnightCHB** [comment]
Hey,I am using this model and ctb5.1 too.
Could I have your email? I want to ask you some questions. :-)

**Comment by HongyanJiao** [comment]
Sure，jiaohongyan0815@163.com



---Original---
