### ISSUE TITLE
No tensorflow 2.0 support?

### ISSUE THREAD

**Issue by alex-calderwood** [nikitakit/self-attentive-parser#54]
I'm getting the error `AttributeError: module 'tensorflow' has no attribute 'GraphDef'` which appears to be an error resulting from using tensorflow 2.0. Is there any plan to add support for tensorflow 2.0? In the meantime what should I do to fix this?

**Comment by ValNyz** [comment]
You can replace some in base_parser.py:
`tf.GraphDef by tf.compat.v1.GraphDef`
and
`tf.Session by tf.compat.v1.Session`

**Comment by interrogator** [comment]
Open PR to fix this is #44
