### ISSUE TITLE
Parsing tagged text

### ISSUE THREAD

**Issue by thorunna** [nikitakit/self-attentive-parser#67]
Hi,

I'm trying to parse input text which has already been tagged using a model that includes a tagger. For this experiment, I'd like to disregard the tagger included in the parsing model but make the parser use the existing tags for tagging the text. Is this possible?

**Comment by jkallini** [comment]
@thorunna Did you have any luck finding out if this is possible?

**Comment by thorunna** [comment]
@jkallini No I didn't, but please let me know if you have any!

**Comment by nikitakit** [comment]
As of benepar 0.2.0a0, there is a [new API integrated with NLTK](https://github.com/nikitakit/self-attentive-parser/blob/4041dde6fedf008dff315d72e29aa2473dfce166/README.md#usage-with-nltk) that can more easily handle parsing text with existing tags. If the `tags` field of `benepar.InputSentence` is not None, the provided tags will be passed through to the output (but if the `tags` field *is* None, benepar will do its own pos tagging).

**Comment by jkallini** [comment]
> As of benepar 0.2.0a0, there is a [new API integrated with NLTK](https://github.com/nikitakit/self-attentive-parser/blob/4041dde6fedf008dff315d72e29aa2473dfce166/README.md#usage-with-nltk) that can more easily handle parsing text with existing tags. If the `tags` field of `benepar.InputSentence` is not None, the provided tags will be passed through to the output (but if the `tags` field _is_ None, benepar will do its own pos tagging).

Hi Nikita,
I see that version 0.2.0a0 does not have this feature with spaCy integration, which is the recommended way to use benepar. Are there any benefits to using spaCy integration if I am parsing English corpus data that is already tokenized and POS tagged by a human? I just want to make sure--will I have better results if I use the existing tags but integrate with NLTK instead of starting with raw text and using spaCy?

**Comment by nikitakit** [comment]
With spaCy, you should be able to do the following to disable benepar's POS tagger and fall back on spaCy's instead.
```
if spacy.__version__.startswith('2'):
    nlp.add_pipe(benepar.BeneparComponent("benepar_en3", disable_tagger=True))
else:
    nlp.add_pipe("benepar", config={"model": "benepar_en3", "disable_tagger": True})
```

You can also inject your own POS tags into spaCy:
```
for i in range(len(spacy_sent)):
    spacy_sent[i].tag_ = my_tags[i]  # my_tags[i] is a string, e.g. NN
```
