### ISSUE TITLE
French model not available ?

### ISSUE THREAD

**Issue by yannis1962** [nikitakit/self-attentive-parser#79]
When I try to download the French model, as indicated in the documentation, I get:

```
python3.9
Python 3.9.4 (default, Apr  5 2021, 01:50:46) 
[Clang 12.0.0 (clang-1200.0.32.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import benepar
>>> benepar.download('benepar_fr')
[nltk_data] Error loading benepar_fr: Package 'benepar_fr' not found
[nltk_data]     in index
False
>>> 

```
Can you please tell me how to download the French model? Thanks in advance!

**Comment by yannis1962** [comment]
I tried it also with an older version of Python and got the same result:
```
Python 3.8.3 (default, May 19 2020, 13:54:14) 
[Clang 10.0.0 ] :: Anaconda, Inc. on darwin

```

**Comment by nikitakit** [comment]
Starting with benepar 0.2.0, you should use `benepar_fr2` instead. It looks like this is my mistake in not updating the README, let me fix that.

Edit: README now fixed, thank you for pointing this out!

**Comment by yannis1962** [comment]
It works, thanks!
